[project]
name = "multi-resource-limiter"
version = "0.1.0"
description = "Robust Asyncio Rate Limiter for Complex API Quotas (Tokens, Requests, etc.)."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["redis>=5.2.1"]
